services:
  postgres-football:
    image: postgres:12.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./installation/sql_scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  populate-teams:
    build: ./installation/populate_teams
    environment:
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
    depends_on:
      - postgres-football

  streamlit-app:
    build: .
    environment:
      FOOTBALL_API_KEY: ${FOOTBALL_API_KEY}
    ports:
      - "8501:8501"
    depends_on:
      - postgres-football

volumes:
  postgres-data:
  # postgres-db-volume: